# Generated by Django 3.0.4 on 2020-05-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('area', models.CharField(max_length=200, null=True)),
                ('date_climbed', models.DateField(null=True)),
            ],
        ),
    ]
